stages:
- stage: Apply_Devops
  jobs:
  - deployment: Apply_Devops
    environment: 
     name: apply_devops
    strategy:
      runOnce:
        deploy:
          steps:
          - bash: terraform apply -var-file=./terraform.tfvars -auto-approve
            workingDirectory: '$(Pipeline.Workspace)/s/environments/devops'
            displayName: 'Terraform ApplyDevops'

