stages:
- stage: Apply_devops
  jobs:
  - deployment: Apply_devops
#     pool: Default
    environment: 
     name: apply_devops
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello

