stages:
  jobs:
   - job: Plan
   - template: ../environments/devops/*  
     steps:
       - name: Terraform Init
         run: terraform init
      
       - name: Terraform plan
         run: terraform plan
