stages:
 - stage: plan 
   jobs:
   - job: Terreform Plan
   - template: ../environments/devops/plan.yml  
     steps:
       - name: Terraform Init
         run: terraform init
      
       - name: Terraform plan
         run: terraform plan
