stages:
- stage: plan
  jobs:
  - job: TerreformPlan
    steps:
    - bash: terraform init
      workingDirectory: '$(Pipeline.Workspace)/s/environments/devops'
      displayName: 'Terraform Init'
    - bash: terraform plan -var-file=./terraform.tfvars
      workingDirectory: '$(Pipeline.Workspace)/s/environments/devops'
      displayName: 'Terraform plan'

